apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    team: opendatahub
  name: kafkaservicemonitor
  namespace: opendatahub
spec:
  endpoints:
    - port: prometheus
  selector: {}
