apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sparkapplications.radanalytics.io.crd.yaml
- sparkclusters.radanalytics.io.crd.yaml
- sparkhistoryservers.radanalytics.io.crd.yaml
- service-account.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
namespace: opendatahub
