apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: odhservicemonitor
  labels:
    team: opendatahub
  namespace: opendatahub
spec:
  selector: {}
  endpoints:
    - port: web
