apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cronworkflow-crd.yaml
- workflow-crd.yaml
- workflowtmp-crd.yaml
- sa-argo.yaml
- sa-argo-server.yaml
- argo-role.yaml
- argo-server-role.yaml
- argo-rolebinding.yaml
- argo-server-binding.yaml
- workflow-configmap.yaml
- service-argo-server.yaml
- service-workflow-controller.yaml
- deployment-argo-server.yaml
- deployment-workflow-controller.yaml
namespace: opendatahub
commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: odhargo
generatorOptions:
  disableNameSuffixHash: true
