apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
namespace: opendatahub
images:
- name: quay.io/radanalyticsio/spark-operator
  newTag: 1.0.7
  newName: quay.io/radanalyticsio/spark-operator
