apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator
  namespace: opendatahub
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: prometheus-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.32.0
